# Metadata for the actions workflow
name: "Docs CI"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

# Environment variables that will be set on all runners
env:
  DEV_SHELL_LINUX: "nix --store ~/nix_store develop '.#ci'"
  DEV_SHELL_MACOS: "nix develop '.#ci'"

# Configuration for individual jobs
jobs:
  # This job checks the formatting of the code and other artifacts.
  formatting:
    name: "Check Docs Formatting"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Lix
        shell: bash
        run: |
          curl -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm
      - name: Restore Nix Cache
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: |
            ~/nix_store
          key: nix-${{ hashFiles('**/flake.lock') }}-ubuntu-latest
      - name: Build Lix Dependencies
        shell: bash
        run: |
          ${{ env.DEV_SHELL_LINUX }}
      - name: Install Node Deps
        shell: bash
        run: |
          ${{ env.DEV_SHELL_LINUX }} --command npm install
      - name: Lint Documentation
        shell: bash
        run: |
          ${{ env.DEV_SHELL_LINUX }} --command npx prettier --check .

  licensing:
    name: "Check Licenses"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          manifest-path: ./Cargo.toml
          command: check
